language: php

php:
  - 5.5.9
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - hhvm
  - nightly

sudo: false

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
    - php: 7.4

before_install:
- echo "memory_limit=3G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - if [ ${TRAVIS_PHP_VERSION} == "5.5.9" ]; then
        travis_retry composer require laravel/framework "5.2.*";
    elif [ ${TRAVIS_PHP_VERSION} == "5.6" ]; then
        travis_retry composer require laravel/framework "5.4.*";
    elif [ ${TRAVIS_PHP_VERSION} == "7.0" ]; then
        travis_retry composer require laravel/framework "5.5.*";
    else
        travis_retry composer update --no-interaction --prefer-source;
    fi

script: make test
