name: PHP Composer
permissions:
  contents: read

#whenever master has a PR or is pushed to
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php-versions: '8.1'
            laravel-versions: '^6.0'
          - php-versions: '8.2'
            laravel-versions: '^6.0'
          - php-versions: '8.3'
            laravel-versions: '^6.0'
          - php-versions: '8.4'
            laravel-versions: '^6.0'
          - php-versions: '8.5'
            laravel-versions: '^6.0'
          - php-versions: '8.1'
            laravel-versions: '^7.0'
          - php-versions: '8.2'
            laravel-versions: '^7.0'
          - php-versions: '8.3'
            laravel-versions: '^7.0'
          - php-versions: '8.4'
            laravel-versions: '^7.0'
          - php-versions: '8.5'
            laravel-versions: '^7.0'
          - php-versions: '8.1'
            laravel-versions: '^8.0'
          - php-versions: '8.2'
            laravel-versions: '^8.0'
          - php-versions: '8.3'
            laravel-versions: '^8.0'
          - php-versions: '8.4'
            laravel-versions: '^8.0'
          - php-versions: '8.5'
            laravel-versions: '^8.0'
          - php-versions: '8.1'
            laravel-versions: '^9.0'
          - php-versions: '8.2'
            laravel-versions: '^9.0'
          - php-versions: '8.3'
            laravel-versions: '^9.0'
          - php-versions: '8.4'
            laravel-versions: '^9.0'
          - php-versions: '8.5'
            laravel-versions: '^9.0'
          - php-versions: '8.1'
            laravel-versions: '^10.0'
          - php-versions: '8.2'
            laravel-versions: '^10.0'
          - php-versions: '8.3'
            laravel-versions: '^10.0'
          - php-versions: '8.4'
            laravel-versions: '^10.0'
          - php-versions: '8.5'
            laravel-versions: '^10.0'
          - php-versions: '8.2'
            laravel-versions: '^11.0'
          - php-versions: '8.3'
            laravel-versions: '^11.0'
          - php-versions: '8.4'
            laravel-versions: '^11.0'
          - php-versions: '8.5'
            laravel-versions: '^11.0'
          - php-versions: '8.2'
            laravel-versions: '^12.0'
          - php-versions: '8.3'
            laravel-versions: '^12.0'
          - php-versions: '8.4'
            laravel-versions: '^12.0'
          - php-versions: '8.5'
            laravel-versions: '^12.0'

    #set the name for each job
    name: PHP ${{ matrix.php-versions }} with Laravel ${{ matrix.laravel-versions }}
    #set up environment variables used by unit tests
    env:
      AWS_ACCESS_KEY_ID: foo
      AWS_SECRET_ACCESS_KEY: bar
      AWS_CSM_ENABLED: false
    steps:
      #sets up the correct version of PHP with necessary config options
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          ini-values: memory_limit=4G, phar.readonly=false

      #checkout the codebase from github
      - name: Checkout codebase
        uses: actions/checkout@v3

      #require laravel (with conditional platform ignore for PHP 8.5)
      - name: Require laravel
        run: |
          if [[ "${{ matrix.php-versions }}" == "8.5" ]]; then
            composer require laravel/framework:${{ matrix.laravel-versions }} --no-interaction --prefer-dist --no-plugins --ignore-platform-reqs
          else
            composer require laravel/framework:${{ matrix.laravel-versions }} --no-interaction --prefer-dist --no-plugins
          fi

      #run tests
      - name: Run test suite
        run: vendor/bin/phpunit

      #remove laravel
      - name: Remove laravel
        run: |
          composer remove laravel/framework --no-plugins
          rm composer.lock

      #require lumen (with conditional platform ignore for PHP 8.5)
      - name: Require lumen
        run: |
          if [[ "${{ matrix.php-versions }}" == "8.5" ]]; then
            composer require laravel/lumen-framework --no-interaction --prefer-dist --no-plugins --ignore-platform-reqs
          else
            composer require laravel/lumen-framework --no-interaction --prefer-dist --no-plugins
          fi

      #run tests
      - name: Run test suite
        run: vendor/bin/phpunit
