name: PHP Composer

#whenever master has a PR or is pushed to
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        include:
          - php-versions: '5.5'
            laravel-versions: '5.1.*'
          - php-versions: '5.6'
            laravel-versions: '5.1.*'
          - php-versions: '7.0'
            laravel-versions: '5.5.*'
          - php-versions: '7.1'
            laravel-versions: '^5.5'
          - php-versions: '7.2'
            laravel-versions: '^5.5'
          - php-versions: '7.2'
            laravel-versions: '^6.0'
          - php-versions: '7.2'
            laravel-versions: '^7.0'
          - php-versions: '7.3'
            laravel-versions: '^6.0'
          - php-versions: '7.3'
            laravel-versions: '^7.0'
          - php-versions: '7.3'
            laravel-versions: '^8.0'
          - php-versions: '7.4'
            laravel-versions: '^6.0'
          - php-versions: '7.4'
            laravel-versions: '^7.0'
          - php-versions: '7.4'
            laravel-versions: '^8.0'
          - php-versions: '8.0'
            laravel-versions: '^7.0'
          - php-versions: '8.0'
            laravel-versions: '^8.0'
          - php-versions: '8.0'
            laravel-versions: '^9.0'
          - php-versions: '8.1'
            laravel-versions: '^8.0'
          - php-versions: '8.1'
            laravel-versions: '^9.0'
          - php-versions: '8.1'
            laravel-versions: '^10.0'
          - php-versions: '8.2'
            laravel-versions: '^9.0'
          - php-versions: '8.2'
            laravel-versions: '^10.0'

    #set the name for each job
    name: PHP ${{ matrix.php-versions }} with Laravel ${{ matrix.laravel-versions }}
    #set up environment variables used by unit tests
    env:
      AWS_ACCESS_KEY_ID: foo
      AWS_SECRET_ACCESS_KEY: bar
      AWS_CSM_ENABLED: false
    steps:
      #sets up the correct version of PHP with necessary config options
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          ini-values: memory_limit=4G, phar.readonly=false

      #checkout the codebase from github
      - name: Checkout codebase
        uses: actions/checkout@v3

      #require laravel
      - name: Require laravel
        run: composer require laravel/framework:${{ matrix.laravel-versions }} --no-interaction --prefer-dist --no-plugins

      #run tests
      - name: Run test suite
        run: vendor/bin/phpunit

      #remove laravel
      - name: Remove laravel
        run: |
          composer remove laravel/framework --no-plugins
          rm composer.lock

      #require lumen
      - name: Require lumen
        if: ${{ matrix.laravel-versions != '^10.0' && (matrix.php-versions != '^8.0' && matrix.laravel-versions != '^7.0') }}
        run: composer require laravel/lumen-framework:${{ matrix.laravel-versions }} --no-interaction --prefer-dist --no-plugins

      #run tests
      - name: Run test suite
        run: vendor/bin/phpunit